<ActionPanel@BoxLayout>:
    MDFlatButton:
        text:"Open"
        on_press: root.openDialog()
    MDFlatButton:
        text:"Save"
        on_press: root.save()
    MDFlatButton:
        text:"Search"
        on_press: root.searchDialog()
    MDFlatButton:
        text:"Delete"
        on_press: root.deleteDialog()
    MDFlatButton:
        text: "Add record"
        on_press: root.addRecordDialog()