<ActionPanel@StackLayout>:
    MDFlatButton:
        text:"Open"
        on_press: root.openFileDialog()
    MDFlatButton:
        text:"Save"
        on_press: root.saveFileDialog()
    MDFlatButton:
        text: "Add record"
        on_press: root.addRecordDialog()
    MDFlatButton:
        text: "Search"
        id: search_caller
        on_press: root.search_dropdown.open()
    MDFlatButton:
        text: "Delete"
        on_press: root.deleteDialog()